/**
 * Error codes — machine-readable, surfaced in OpenAPI, used by the FE to branch on `code`.
 * Rules: append-only, never reuse or renumber a deleted code, RESOURCE_REASON convention.
 */

export const ErrorCodes = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_CURSOR: 'INVALID_CURSOR',
  INVALID_FILTER: 'INVALID_FILTER',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // Auth / Identity
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_REFRESH_TOKEN_REUSE: 'AUTH_REFRESH_TOKEN_REUSE',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  SSO_NOT_CONFIGURED: 'SSO_NOT_CONFIGURED',
  SSO_TOKEN_INVALID: 'SSO_TOKEN_INVALID',
  SSO_CLAIMS_MISSING: 'SSO_CLAIMS_MISSING',
  SSO_TENANT_NOT_FOUND: 'SSO_TENANT_NOT_FOUND',
  SSO_CONNECTION_DISABLED: 'SSO_CONNECTION_DISABLED',
  SSO_DOMAIN_NOT_ALLOWED: 'SSO_DOMAIN_NOT_ALLOWED',
  SSO_JIT_DISABLED: 'SSO_JIT_DISABLED',
  SSO_NO_ACCESS: 'SSO_NO_ACCESS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  SIGNUP_DISABLED: 'SIGNUP_DISABLED',

  // Tenant / Workspace
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN: 'WORKSPACE_SLUG_TAKEN',
  WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ALREADY_EXISTS: 'WORKSPACE_MEMBER_ALREADY_EXISTS',

  // Project
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_KEY_TAKEN: 'PROJECT_KEY_TAKEN',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_PERMISSION_DENIED: 'PROJECT_PERMISSION_DENIED',
  PROJECT_LEAD_NOT_MEMBER: 'PROJECT_LEAD_NOT_MEMBER',
  LABEL_NOT_FOUND: 'LABEL_NOT_FOUND',

  // Work item
  WORK_ITEM_NOT_FOUND: 'WORK_ITEM_NOT_FOUND',
  WORK_ITEM_RANK_CONFLICT: 'WORK_ITEM_RANK_CONFLICT',
  WORK_ITEM_INVALID_TRANSITION: 'WORK_ITEM_INVALID_TRANSITION',
  WORK_ITEM_INVALID_PARENT_TYPE: 'WORK_ITEM_INVALID_PARENT_TYPE',
  WORK_ITEM_CIRCULAR_PARENT: 'WORK_ITEM_CIRCULAR_PARENT',
  WORK_ITEM_MAX_DEPTH_EXCEEDED: 'WORK_ITEM_MAX_DEPTH_EXCEEDED',
  WORK_ITEM_PARENT_SCOPE_MISMATCH: 'WORK_ITEM_PARENT_SCOPE_MISMATCH',
  WORK_ITEM_STORY_HAS_NO_PRIORITY: 'WORK_ITEM_STORY_HAS_NO_PRIORITY',
  WORK_ITEM_NOT_BACKLOG_TYPE: 'WORK_ITEM_NOT_BACKLOG_TYPE',
  WORK_ITEM_EMPTY_SELECTION: 'WORK_ITEM_EMPTY_SELECTION',

  // Workflow
  WORKFLOW_STATUS_NOT_FOUND: 'WORKFLOW_STATUS_NOT_FOUND',
  WORKFLOW_TRANSITION_NOT_ALLOWED: 'WORKFLOW_TRANSITION_NOT_ALLOWED',

  // Sprint / Planning (legacy — reporting module still speaks Sprint; Phase 5)
  SPRINT_NOT_FOUND: 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE: 'SPRINT_ALREADY_ACTIVE',
  SPRINT_PROJECT_MISMATCH: 'SPRINT_PROJECT_MISMATCH',

  // Iteration (Rally timeboxes — Phase 2)
  ITERATION_NOT_FOUND: 'ITERATION_NOT_FOUND',
  ITERATION_NOT_PLANNING: 'ITERATION_NOT_PLANNING',
  ITERATION_NOT_COMMITTED: 'ITERATION_NOT_COMMITTED',
  ITERATION_ALREADY_COMMITTED: 'ITERATION_ALREADY_COMMITTED',
  ITERATION_PROJECT_MISMATCH: 'ITERATION_PROJECT_MISMATCH',
  ITERATION_TEAM_MISMATCH: 'ITERATION_TEAM_MISMATCH',
  ITERATION_INVALID_DATE_RANGE: 'ITERATION_INVALID_DATE_RANGE',

  // Release
  RELEASE_NOT_FOUND: 'RELEASE_NOT_FOUND',
  RELEASE_PROJECT_MISMATCH: 'RELEASE_PROJECT_MISMATCH',

  // Access / Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ASSIGNMENT_NOT_FOUND: 'ROLE_ASSIGNMENT_NOT_FOUND',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  // Password reset
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',

  // Workspace invitations
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  SOLE_ADMIN_VIOLATION: 'SOLE_ADMIN_VIOLATION',

  // Teams
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_KEY_TAKEN: 'TEAM_KEY_TAKEN',
  TEAM_ALREADY_ARCHIVED: 'TEAM_ALREADY_ARCHIVED',
  TEAM_MEMBER_NOT_FOUND: 'TEAM_MEMBER_NOT_FOUND',
  TEAM_MEMBER_ALREADY_EXISTS: 'TEAM_MEMBER_ALREADY_EXISTS',

  // Project teams / members
  PROJECT_TEAM_ALREADY_LINKED: 'PROJECT_TEAM_ALREADY_LINKED',
  PROJECT_TEAM_LINK_NOT_FOUND: 'PROJECT_TEAM_LINK_NOT_FOUND',
  PROJECT_MEMBER_NOT_FOUND: 'PROJECT_MEMBER_NOT_FOUND',
  PROJECT_MEMBER_ALREADY_EXISTS: 'PROJECT_MEMBER_ALREADY_EXISTS',
  ASSIGNEE_NOT_WORKSPACE_MEMBER: 'ASSIGNEE_NOT_WORKSPACE_MEMBER',

  // Collaboration
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',

  // Milestones
  MILESTONE_NOT_FOUND: 'MILESTONE_NOT_FOUND',
  ATTACHMENT_NOT_PENDING: 'ATTACHMENT_NOT_PENDING',
  ATTACHMENT_SIZE_MISMATCH: 'ATTACHMENT_SIZE_MISMATCH',
  ATTACHMENT_FILE_TOO_LARGE: 'ATTACHMENT_FILE_TOO_LARGE',
  ATTACHMENT_INVALID_TYPE: 'ATTACHMENT_INVALID_TYPE',
  ATTACHMENT_LIMIT_EXCEEDED: 'ATTACHMENT_LIMIT_EXCEEDED',
  ATTACHMENT_NOT_OWNER: 'ATTACHMENT_NOT_OWNER',
  COMMENT_NOT_OWNED: 'COMMENT_NOT_OWNED',
  TIME_LOG_NOT_FOUND: 'TIME_LOG_NOT_FOUND',
  TIME_LOG_NOT_OWNER: 'TIME_LOG_NOT_OWNER',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Audit
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',

  // Reporting
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ErrorCategory =
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'VALIDATION_FAILED'
  | 'PERMISSION_DENIED'
  | 'PRECONDITION_FAILED'
  | 'RATE_LIMITED'
  | 'UNAUTHORIZED'
  | 'INTERNAL';

export const CATEGORY_HTTP_STATUS: Record<ErrorCategory, number> = {
  NOT_FOUND: 404,
  CONFLICT: 409,
  VALIDATION_FAILED: 422,
  PERMISSION_DENIED: 403,
  PRECONDITION_FAILED: 412,
  RATE_LIMITED: 429,
  UNAUTHORIZED: 401,
  INTERNAL: 500,
};
